### ISSUE TITLE
For what resolution and UI size should I use it?

### ISSUE THREAD

**Issue by ghost** [rbrasga/TLFishingBot#4]

**Comment by ryantuludjian** [comment]
Hello did you figure out what resolution and UI size?

**Comment by toscosan** [comment]
Disponibiliza o .exe para download, e a versão em FDH 1920X1080 PLIS

**Comment by rbrasga** [comment]
Sorry, I never noticed this. I'm using a 1440p monitor. I made a few changes to the UI like smaller font size.

If it doesn't work out-of-the-box, you can take screenshots and modify the coordinates and/or pictures.

I thought about making this easier (OCR - object character recognition, flexible regardless of UI/resolution, a simple executable binary instead of a script that requires python to run), but I don't want thousands of people using this. It was just meant as a prototype.
